### ISSUE TITLE
Windows Defender detects trojan

### ISSUE THREAD

**Issue by eldritchgreene** [nod5/BookCrop#2]
When I try to download the .exe it is blocked by Windows Defender claiming trojan Occamy.CDB 
I know this is likely a false positive but worth checking.

**Comment by nod5** [comment]
Sorry for very late reply. Yes it is a false positive.
**Q** My browser or security app blocks the `.exe` file or warn about it?  
**A** Compiled AutoHotkey programs are sometimes [incorrectly flagged](https://www.autohotkey.com/docs/FAQ.htm#Virus ). You can alternatively install [AutoHotkey](https://www.autohotkey.com/) and compile the `.ahk` source file yourself (easy!) or run the `.ahk` source directly (even easier!).
